### ISSUE TITLE
WINDOWS: Why not using bdashore3/flash-attention ?

### ISSUE THREAD

**Issue by RGX650** [dicksondickson/ComfyUI-Clean-Install#1]
I am on Windows,
i always used bdashore3 fork

https://github.com/bdashore3/flash-attention.git

**Comment by dicksondickson** [comment]
I do no know of that fork. What is your experience with it? Looking at his commit history, it seems like he made some specific changes for windows.

**Comment by dicksondickson** [comment]
I took a look at the code more closely and it seems he doesn't change any of the Flash Attention code - just building the binary wheels. Closing this as my batch files are for people that want to compile themselves.
