### ISSUE TITLE
Would it be relevant: to compile in an empty venv?

### ISSUE THREAD

**Issue by RGX650** [dicksondickson/ComfyUI-Clean-Install#2]
:: EXAMPLE for ComfyUI_windows_portable - using specific pytorch version - python310

set comfyDir=C:\AI\COMFYUI\ComfyUI_windows_portable
set sandboxDir=C:\AI\COMFYUI\ComfyUI_windows_portable\sandbox

:: make sandboxDir directory
cd %comfyDir%
mkdir sandbox

cd %sandboxDir%

:: activate venv
python -m venv venv
call venv/Scripts/activate

pip install packaging
pip install wheel
pip install ninja
python.exe -m pip install --upgrade pip

:: install specific pytorch version
pip install torch==2.3.0+cu121 torchaudio==2.3.0+cu121 torchvision==0.18.0+cu121 --index-url https://download.pytorch.org/whl/cu121

:: clone flash attention bdashore3
git clone https://github.com/bdashore3/flash-attention.git
cd flash-attention

:: set the number of threads. 10 jobs uses 60gigs of ram at peak
set MAX_JOBS=4

:: start compile
:: python setup.py install

:: build wheel
python setup.py bdist_wheel

:: exit sandbox and switch to comfy
cd %sandboxDir%
call venv/Scripts/deactivate
cd %comfyDir%\python_embeded

:: pip install new-package.whl
python -m pip install %sandboxDir%\flash-attention\dist\flash_attn-2.5.9.post1-cp310-cp310-win_amd64.whl

pause

**Comment by dicksondickson** [comment]
You certainly can and it wouldn't hurt. My systems are dedicated to comfy so I don't do it. But I would definitely do that for my main workstation though.
